# when testing a site, the config is used by the local supervisor
site: config/ci/rsmp_gem.yaml

# when testing a supervisor, the config is used by the local site
supervisor: config/ci/rsmp_supervisor.yaml
