# when testing a site, config describes the local supervisor
config:       config/ci/rsmp_gem.yaml

# when testing a supervisor, config describes the local site
#config: config/ci/rsmp_supervisor.yaml
