# Config for testing a supervisor running on localhost (e.g. one from the rsmp gem)
# The settings are used for starting a local site connecting to the supervisor tested
type: tlc
site_id: RN+SI0001
supervisors:
  - ip: 127.0.0.1
    port: 13111
sxl: tlc
sxl_version: 1.0.15
components:
  main:
    TC:
      cycle_time: 6
  signal_group:
    A1:
      plan: '11NBBB'
    A2:
      plan: '1NBBBB'
    B1:
      plan: 'BBB11N'
    B2:
      plan: 'BBB1NB'
  detector_logic:
    DL1:
intervals:
  timer: 0.1
  watchdog: 0.1
  reconnect: 0.1
timeouts:
  connect: 1
  ready: 1
  watchdog: 0.2
  acknowledgement: 0.2
restrict_testing:
  core_version: 3.1.5
  sxl_version: 1.0.15
secrets:
  security_codes:
    1: '1111'
    2: '2222'
