supervisor:
  port: 13111
  sites:
    :any:
      rsmp_versions:
        - 3.1.1
        - 3.1.2
      plans:
        - 1
        - 2
      traffic_situations:
        - 1
        - 2
      emergency_routes:
        - 1
      inputs:
        - 1
      components:
        main:
          TC:
        signal_group:
          A1:
          A2:
          B1:
          B2:
        detector_logic:
          DL1:
  watchdog_interval: 0.1
  watchdog_timeout: 1
  acknowledgement_timeout: 1
  command_response_timeout: 1
  status_response_timeout: 1
  status_update_timeout: 1

connect_timeout: 1
ready_timeout: 1
status_update_rate: 0   # rsmp only allow integer update rates
subscribe_timeout: 1
alarm_timeout: 1
shutdown_timeout: 1
command_timeout: 1
