supervisor:
  sites:
    :any:
      plans:
        - 1
        - 2
      traffic_situations:
        - 1
        - 2
      emergency_routes:
        - 1
      inputs:
        - 1
      components:
        main:
          TC:
        signal_group:
          A1:
          A2:
          B1:
          B2:
        detector_logic:
          DL1:
  watchdog_interval: 0.1
  watchdog_timeout: 0.2
  acknowledgement_timeout: 0.2
  command_response_timeout: 0.2
  status_response_timeout: 0.2
  status_update_timeout: 0.2

connect_timeout: 0.2
ready_timeout: 0.2
status_update_rate: 0   # rsmp only allow integer update rates
subscribe_timeout: 0.2
alarm_timeout: 0.2
shutdown_timeout: 0.2

