supervisor:
  sites:
    :any:
      rsmp_versions:
        - 3.1.1
        - 3.1.2
      plans:
        - 1
        - 2
      traffic_situations:
        - 1
        - 2
      emergency_routes:
        - 1
      inputs:
        - 1
      components:
        main:
          TC:
        signal_group:
          A1:
          A2:
          B1:
          B2:
        detector_logic:
          DL1:
  watchdog_interval: 0.1
  watchdog_timeout: 0.2
  acknowledgement_timeout: 0.2
  command_response_timeout: 0.2
  status_response_timeout: 0.2
  status_update_timeout: 0.2

scripts:
  activate_alarm: /home/seguro/RSMP/scripts/activate_alarm.sh
  deactivate_alarm: /home/seguro/RSMP/scripts/deactivate_alarm.sh

connect_timeout: 0.2
ready_timeout: 0.2
status_update_rate: 0   # rsmp only allow integer update rates
subscribe_timeout: 0.2
alarm_timeout: 0.2
shutdown_timeout: 0.2
command_timeout: 0.2

