supervisor:
  sites:
    :any:
      plans:
        - '8'
        - '9'
      traffic_situation:
        - '1'
        - '2'
      emergency_route:
        - '1'
      components:
        :any:
          traffic_controller: 'KK+AG9998=001TC000'
          signal_group_prefix: 'KK+AG9998=001SG'
          detector_logic_prefix: 'KK+AG9998=001DL'
  watchdog_interval: 60
  watchdog_timeout: 120
  acknowledgement_timeout: 20
  command_response_timeout: 20
  status_response_timeout: 20
  status_update_timeout: 20

connect_timeout: 120
ready_timeout: 10

command_timeout: 180
status_timeout: 180
subscribe_timeout: 180
alarm_timeout: 180
