supervisor:
  sites:
    :any:
      plans:
        - 8
        - 9
      traffic_situations:
        - 1
        - 2
      emergency_routes:
        - 1
      inputs:
        - 1
      components:
        main:
          KK+AG9998=001TC000:
        signal_group:
          KK+AG9998=001SG001:
        detector_logic:
          KK+AG9998=001DL001:
  watchdog_interval: 60
  watchdog_interval: 60
  watchdog_timeout: 120
  acknowledgement_timeout: 20
  command_response_timeout: 20
  status_response_timeout: 20
  status_update_timeout: 20

connect_timeout: 120
ready_timeout: 10

command_timeout: 180
status_timeout: 180
subscribe_timeout: 180
alarm_timeout: 180
shutdown_timeout: 180
