# This workflow will rebuild YARD docs and update the gh-pages branch.

name: Build Documentation

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build YARD doc and update the gh-pages branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          ref: gh-pages

      - name: Install dependencies
        run: bundle

      - name: Update YARD docs
        run: git checkout master --no-overlay -- docs
        run: bundle exec yardoc

#      - name: Commit changes
#        uses: EndBug/add-and-commit@v7
#        with:
#          default_author: github_actor
#          message: 'Automatically update documentation'
#          add: 'docs'