# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will run rspec

name: Dynniq EC-2

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  test:

    runs-on: [ self-hosted, Windows, X64, ec2 ]
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Configure test
      run: |
        "rsmp_config_path: config/ci/dynniq_ec2.yaml" | Out-File 'config/validator.yaml' -Encoding utf8
    - name: Set up secrets
      run: |
        echo "security_codes:`n    1: ''`n    2: ''" > config/secrets.yaml
    - name: Set up ruby
      uses: ruby/setup-ruby@v1
      env:
        ImageOS: win19
      with:
        ruby-version: 3.0
        bundler-cache: true # runs 'bundle install' and caches installed gems
    - name: Run tests
      run: bundle exec rspec spec/site
    - name: Rename validation.log
      if: always()
      run: mv log/validation.log log/validation_ec2_$(date +%F_%H-%M-%S).log
    - name: Upload validation.log
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: rspec validation
        path: log/validation_ec2_*.log
    - name: Get ec2 rsmp log
      if: always()
      env:
        user: ${{ secrets.EC2_USER }}
        passwd: ${{ secrets.EC2_PASSWD }}
        ip: ${{ secrets.EC2_IP }}
      run: |
        Remove-Item Alias:curl
        curl -u $user":"$passwd "ftp://$ip/tmp/proxyapp.log" -o simulator.log
    - name: Upload ec2 rsmp log
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: ec2 rsmp log
        path: simulator.log
