# Run equipment tests in rsmp_implementations

name: Remote Dispatch Action Initiator

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
  repository_dispatch:

jobs:
  equipment_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Run equipment tests in rsmp_implementations
        run: |
          curl -X POST https://api.github.com/repos/rsmp-nordic/rsmp_implementations/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.ACCESS_TOKEN }} \
          --data '{"event_type": "trigger_equipment_tests", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'
