# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will run rspec

name: Swarco ITC-2

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  test:

    runs-on: [ self-hosted, Linux, X64, itc2 ]
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Configure test
      shell: bash
      run: |
        echo "rsmp_config_path: config/swarco.yaml" > config/validator.yaml
    - name: Set up secrets
      shell: bash
      run: |
        echo -e "security_codes:\n    1: ''\n    2: ''" > config/secrets.yaml
    - name: Configure bundle
      run: bundle config set path '~/rsmp_gems/bundle'
    - name: Run bundle install
      run: bundle install
    - name: Run tests
      run: bundle exec rspec spec/site
  log:

    runs-on: [ self-hosted, Linux, X64, itc2 ]
    needs: test
    if: always()
    steps:
    - name: Upload validation.log
      uses: actions/upload-artifact@v1
      with:
        name: rspec validation
        path: log/validation.log
    - name: Upload itc2 rsmp log
      uses: actions/upload-artifact@v1
      with:
        name: itc2 rsmp log
        path: /tmp/simulator.log
