# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will run rspec

name: Swarco ITC-3
on:
  pull_request:
    types: [ labeled ]
  schedule:
    # schedule runs only on the default branch. time is in UTC.
    # * is a special character in YAML so you have to quote this string.
    # run every night at 3:45AM UTC.
    - cron:  '45 0 * * *'
jobs:
  test:
    if: ${{ github.event_name == 'schedule' || github.event.label.name == 'equipment' }}
    runs-on: [ self-hosted, Linux, X64, itc3 ]
    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Run tests
      run: bundle exec rspec --format Validator::Brief --format Validator::Details --out log/validation.log spec/site/tlc
      env:
        SITE_CONFIG: config/swarco_itc3.yaml

    - name: Show detailed log
      if: always()
      run: cat log/validation.log

    - name: Rename validation.log
      if: always()
      run: |
        $date=Get-Date -Format 'yyyy-MM-dd_HH-mm'
        mv log/validation.log log/validation_itc3_$date.log

    - name: Upload validation.log
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: rspec-validation
        path: log/validation_itc3_*.log
